### ISSUE TITLE
數數顯示錯誤

### ISSUE THREAD

**Issue by Edit-Mr** [SCAICT/SCAICT-uwu#11]
**問題說明 Describe the feature**
你有什麼問題？ A clear and concise description of what the bug is.

如果輸入內容根本不是 16 進位不會報錯

**To Reproduce**
重現錯誤的步驟 Steps to reproduce the behavior:
1. 打 gg

**Expected behavior**
你想要怎樣？ A clear and concise description of what you expected to happen.

回應❌

**Screenshots**
若你覺得有幫助可以截圖 If applicable, add screenshots to help explain your problem.

**Additional context**
還有什麼想說的？ Add any other context about the problem here.

**Comment by iach526526** [comment]
OK,I changed it!

**Comment by Edit-Mr** [comment]
@iach526526 我順便加了排除數數的電電點統計
