### ISSUE TITLE
猜拳遊戲的冷卻機制

### ISSUE THREAD

**Issue by JustappleJust** [SCAICT/SCAICT-uwu#36]
## 你想怎樣？ What do you want?
猜拳遊戲加入一定時間的冷卻
或是稍微調整機率
## 為什麼？ Why?
連續瘋狂猜拳大概率會賺ouo
然後就會出現瘋狂洗版的現象.w.

**Comment by Edit-Mr** [comment]
剪刀、石頭、布的機率皆為 1/3，期望值為 0。如果真的有大賺的話，那麼你運氣很好。

**Comment by Edit-Mr** [comment]
@winstonsung ?

**Comment by winstonsung** [comment]
resolved/closed by的概念，不是completed/done by。
