### ISSUE TITLE
Fix the mess in database 清理資料庫問題

### ISSUE THREAD

**Issue by winstonsung** [SCAICT/SCAICT-uwu#47]
**問題說明 Describe the issue**

- Fix the mess in database naming 清理資料庫命名問題
  - We should always use `snake_case` for database, table, column, trigger names.
  - Table names and column names may NOT be case-sensitive in SQLite.
  - Database, table, and trigger names may NOT be case-sensitive in MySQL/MariaDB.
- 使用單一資料庫而非多個
  - `ctf`: `USE CTF`
  - `dcsqltest`: `USE DCSQLtest`
```[tasklist]
### Tasks
- [ ] https://github.com/SCAICT/SCAICT-uwu/issues/103
```

**Comment by winstonsung** [comment]
測試結果： MySQL/MariaDB似乎不論 `CREATE` 時輸入大小寫都會自動轉換成小寫。

**Comment by winstonsung** [comment]
> https://dev.mysql.com/doc/refman/8.4/en/identifier-case-sensitivity.html
>
> How table and database names are stored on disk and used in MySQL is affected by the lower_case_table_names system variable. lower_case_table_names can take the values shown in the following table. This variable does not affect case sensitivity of trigger identifiers. On Unix, the default value of lower_case_table_names is 0. On Windows, the default value is 1. On macOS, the default value is 2.

**Comment by iach526526** [comment]
fix it at this [commit](https://github.com/SCAICT/SCAICT-uwu/commit/b5fa76d146b791f3a95e4f51f222ce4a442a2e8e)
