### ISSUE TITLE
統一電電點 emoji

### ISSUE THREAD

**Issue by Edit-Mr** [SCAICT/SCAICT-uwu#68]
把電電點使用 :zap: ⚡️emoji 全部改成電電點 emoji

![image](https://github.com/SCAICT/SCAICT-uwu/assets/61068739/87181af4-3f1b-4bdd-a4b4-2a855954ff92)

**Comment by iach526526** [comment]
Already done at [this commit](https://github.com/SCAICT/SCAICT-uwu/commit/bdcdac3831ebd0405ebffe7cb7e6d5e30a09393d)
