### ISSUE TITLE
/發送禮物 指令的預期外錯誤

### ISSUE THREAD

**Issue by iach526526** [SCAICT/SCAICT-uwu#89]
**問題說明 Describe the feature**
重新啟動中電喵後， dm 按鈕存放的電電點或抽獎劵會過期
**To Reproduce**
重現錯誤的步驟 Steps to reproduce the behavior:

1.使用 ```/發送禮物```送電電點給某個人
2.重新啟動中電喵
3.領取電電點，查看電電點 log 資料庫
4.發現這個 bug

**Expected behavior**
你想要怎樣？ A clear and concise description of what you expected to happen.
修好它
**Additional context**
還有什麼想說的？ Add any other context about the problem here.
希望 pylint 不要再沒過了，這就像夢回國小重寫甲乙本

**Comment by winstonsung** [comment]
~~那個Pylint要是過了就是發給5個人的禮物變成5份禮物全部發給1個人（）。~~

**Comment by iach526526** [comment]
是嗎？我有測試發同時發給我之外的其他人，功能是沒問題的。 lambda 裡面只是在把 Discord 名稱映射成 Discord id 發起私訊
https://github.com/SCAICT/SCAICT-uwu/pull/83/commits/f0b47e82f852144927869ba5f9a1098b4eefc983

**Comment by winstonsung** [comment]
後來看了一下Stackoverflow裡面，似乎是有一些lambda的特例會誤報。

**Comment by iach526526** [comment]
PR: https://github.com/SCAICT/SCAICT-uwu/pull/90
create a SQL table store button id and its content.
